language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

group: travis_latest

git:
  depth: 3


install: pip -q install -e .[tests] --process-dependency-links

script: 
  - pytest
  - coverage run tests/test_all.py -v

after_success: coveralls
